name: Hello World

on:
  push:
    branches:
      - 'master'
    pull_request:
      branches:
        - 'master'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        uses: echo "Hello World"

